//go:build !lib

// Source mode: compile C sources directly with CGO.
// Usage: go build (default)
// Requires: CGO_CFLAGS_ALLOW="-mavx.*|-msse.*|-mfma|-mavx512.*"
// Generated by CMake - DO NOT EDIT MANUALLY
package matrix

/*
#cgo CFLAGS: -I${SRCDIR}/include
#cgo CFLAGS: -I${SRCDIR}/modules/platform/include
#cgo CFLAGS: -I${SRCDIR}/third_party/OpenBLAS
#cgo linux,amd64   LDFLAGS: -L${SRCDIR}/modules/platform/build/linux_amd64 -lfinkit_platform_static -L${SRCDIR}/build/linux_amd64/third_party -lopenblas -lm -lgfortran -lpthread
#cgo linux,arm64   LDFLAGS: -L${SRCDIR}/modules/platform/build/linux_arm64 -lfinkit_platform_static -L${SRCDIR}/build/linux_arm64/third_party -lopenblas -lm -lgfortran -lpthread
#cgo darwin,amd64  LDFLAGS: -L${SRCDIR}/modules/platform/build/darwin_amd64 -lfinkit_platform_static -L${SRCDIR}/build/darwin_amd64/third_party -lopenblas -lm -lgfortran -lpthread
#cgo darwin,arm64  LDFLAGS: -L${SRCDIR}/modules/platform/build/darwin_arm64 -lfinkit_platform_static -L${SRCDIR}/build/darwin_arm64/third_party -lopenblas -lm -lgfortran -lpthread
#cgo windows,amd64 LDFLAGS: -L${SRCDIR}/modules/platform/build/windows_amd64 -lfinkit_platform_static -L${SRCDIR}/build/windows_amd64/third_party -lopenblas -lm -lgfortran -lpthread


#include "matrix.h"
#include "gemm.h"
#include "gemv.h"
#include "decompose.h"
#include "solve.h"
#include "transpose.h"
#include "tridiag.h"
#include "vector_ops.h"

// Matrix sources
#include "matrix-c/decompose.c"
#include "matrix-c/gemm.c"
#include "matrix-c/gemv.c"
#include "matrix-c/solve.c"
#include "matrix-c/transpose.c"
#include "matrix-c/tridiag.c"
#include "matrix-c/vector_ops.c"

// Forward declarations for fc_init/fc_cleanup (no public header)
int fc_init(void);
void fc_cleanup(void);
*/
import "C"

func init() {
	C.fc_init()
}
